#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail

if [ -n ${BAREON_SRC-""} ] ; then
    git clone -b $BAREON_BRANCH $BAREON_SRC $TARGET_ROOT/tmp/bareon

    cd $TARGET_ROOT/tmp/bareon
    git log -25 --oneline > changelog
    cd -
fi