#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


[ -n "$TARGET_ROOT" ]

source $_LIB/img-functions

IMAGE_PATH=$(readlink -f $IMAGE_NAME)
cd $TARGET_ROOT

echo "#disabled" > ./tmp/fstab.new
sudo mv ./tmp/fstab.new ./etc/fstab
sudo ln -s ./sbin/init ./

if [ ! -n ${DIB_MAKE_SQUASHFS-""} ] ; then
	sudo find . -path './sys/*' -prune -o -path './proc/*' -prune -o -path './dev/*' -prune -o -path './tmp/*' -prune -o -print | sudo cpio -o -H newc | gzip > ${IMAGE_PATH}.initramfs

	select_boot_kernel_initrd $TARGET_ROOT
	sudo cp $BOOTDIR/$KERNEL ${IMAGE_PATH}.vmlinuz
else
	select_boot_kernel_initrd $TARGET_ROOT
	sudo cp -a ./boot/initrd* ${IMAGE_PATH}.initramfs
	sudo cp -a ./boot/vmlinuz* ${IMAGE_PATH}.vmlinuz
	sudo rm -f ./boot/initrd*
	sudo rm -f ./boot/vmlinuz*

	if sudo mountpoint -q ./proc ; then
		sudo umount ./proc
	fi

	sudo mksquashfs . ${IMAGE_PATH}.squashfs -noappend -e proc/* dev/* sys/* tmp/*
fi
